my_bedding/cart/urls.py
from django.urls import path


from .views import (cart_add, cart_detail, cart_remove,
                    cart_increase, cart_decrease, update_quantity,
                    get_discount)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart-detail'),
    path('add/<int:article>/', cart_add, name='cart-add'),
    path('remove/<int:article>/', cart_remove, name='cart-remove'),
    path('increase/<int:article>/', cart_increase, name='cart-increase'),
    path('decrease/<int:article>/', cart_decrease, name='cart-decrease'),
    path('update_quantity/<int:article>/', update_quantity, name='update-quantity'),
    # path('status/', cart_status, name='cart-status'),
    path('get_discount/', get_discount, name='get_discount'),
]

my_bedding/my_bedding/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

my_bedding/users/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path

from .views import (get_csrf_token, register, login_user, logout_user, view_account, edit_account,
                    PasswordResetAjaxView, PasswordResetConfirmAjaxView, update_photo, delete_photo)

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('login-html/', login_user, name='login_html'),
    path('logout/', logout_user, name='logout'),
    path('account/', view_account, name='view_account'),
    path('account/edit/', edit_account, name='edit_account'),
    path('get-csrf-token/', get_csrf_token, name='get_csrf_token'),
    path('password-reset/', PasswordResetAjaxView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmAjaxView.as_view(),
         name='password_reset_confirm'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('update-photo/', update_photo, name='update_photo'),
    path('delete-photo/', delete_photo, name='delete_photo'),
]

my_bedding/users/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser

from phonenumber_field.modelfields import PhoneNumberField
from easy_thumbnails.fields import ThumbnailerImageField

from .managers import CustomUserManager
from .validators import (
    validate_russian_phone,
    validate_first_name,
    validate_last_name,
    validate_telegram_id
)


class User(AbstractUser):
    first_name = models.CharField(
        max_length=100,
        blank=True,  # Позволяет оставлять поле пустым в формах
        null=True,  # Позволяет сохранять NULL в базе данных
        verbose_name='Имя',
        validators=[validate_first_name]
    )
    last_name = models.CharField(
        max_length=100,
        blank=True,  # Позволяет оставлять поле пустым в формах
        null=True,  # Позволяет сохранять NULL в базе данных
        verbose_name='Фамилия',
        validators=[validate_last_name]
    )
    # Обязательно уникальный email, так как он используется для аутентификации
    email = models.EmailField(
        unique=True,
        null=False,
        blank=False
    )
    phone_number = models.CharField(
        verbose_name='Телефон',
        unique=True,
        blank=True,
        null=True,
        max_length=12,  # Для номеров типа +7XXXXXXXXXX
        validators=[validate_russian_phone],
    )
    address = models.CharField(
        max_length=250,
        verbose_name='Адрес',
        blank=True,
        null=True,
    )
    username = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()  # Присваиваем кастомный менеджер

    # отображать в админке по email
    def __str__(self):
        return f'id {self.id}'

    # class Meta:
    #     verbose_name = 'Пользователь'
    #     verbose_name_plural = 'Пользователи'


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        on_delete=models.CASCADE,
        related_name='profile',
        verbose_name='Профиль пользователя',
    )
    photo = ThumbnailerImageField(
        upload_to='media/users/',
        verbose_name='Фото',
        null=True,
        blank=True,
    )
    telegram_id = models.CharField(
        max_length=30,
        verbose_name='Telegram-ID',
        unique=True,
        null=True,
        blank=True,
        validators=[validate_telegram_id]
    )

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

my_bedding/users/views.py
import requests
from django.conf import settings
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, PasswordChangeForm
from django.middleware.csrf import get_token
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.decorators.http import require_POST, require_GET

from .context_processors import auth_forms
from .forms import RegisterUserForm, LoginUserForm, UserEditForm, ProfileEditForm, UserPasswordResetForm, \
    UserPasswordChangeForm
from .models import Profile
from .tasks import user_registered


User = get_user_model()


def get_csrf_token(request):
    return JsonResponse({'csrfToken': get_token(request)})


def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        recaptcha_response = request.POST.get('g-recaptcha-response')
        secret_key = settings.RECAPTCHA_SECRET_KEY
        payload = {'secret': secret_key, 'response': recaptcha_response}
        response = requests.post("https://www.google.com/recaptcha/api/siteverify", data=payload)
        result = response.json()
        print(f"reCAPTCHA результат верификации: {result}")
        if not result.get('success'):
            form.add_error('captcha', "Не пройдена captcha.")
        if form.is_valid():
            user = form.save(commit=False)
            raw_password = form.cleaned_data['password']  # Получаем пароль до хэширования
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)
            user_registered.delay(user.id, raw_password)
            if user is not None:
                login(request, user)
            return JsonResponse({'success': True, 'redirect_url': reverse('users:view_account')},
                                status=201)
        else:
            # Возвращаем ошибки в виде JSON
            errors = {field: errors for field, errors in form.errors.items()}
            return JsonResponse({'success': False, 'errors': errors}, status=400)


def login_user(request):
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user and user.is_active:
                login(request, user)
                response = JsonResponse({'success': True, 'message': 'Вход успешно выполнен'}, status=200)
            else:
                response = JsonResponse({'success': False, 'errors': {'password': ['Неверный логин или пароль']}},
                                        status=401)
        else:
            response = JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return response

def logout_user(request):
    logout(request)
    return redirect('shop:product_list')


@require_GET
@login_required(login_url='/')
def view_account(request):
    user = request.user
    profile = user.profile
    user_edit_form = UserEditForm(instance=user)
    profile_edit_form = ProfileEditForm(instance=profile)
    change_password_form = UserPasswordChangeForm(user=user)
    return render(request, 'users/personal_account.html',
                  {'user': user, 'profile': profile, 'user_edit_form': user_edit_form,
                   'profile_edit_form': profile_edit_form, 'change_password_form': change_password_form})


@require_POST
@login_required(login_url='/')
def edit_account(request):
    user = request.user
    profile = user.profile

    user_edit_form = UserEditForm(request.POST, instance=user)
    profile_edit_form = ProfileEditForm(request.POST, request.FILES, instance=profile)
    change_password_form = UserPasswordChangeForm(data=request.POST, user=user)

    # Проверяем, есть ли данные для изменения пароля
    password_fields_filled = all(
        request.POST.get(field) for field in ['old_password', 'new_password1', 'new_password2']
    )

    if user_edit_form.is_valid() and profile_edit_form.is_valid() and change_password_form.is_valid():
        user_edit_form.save()
        profile_edit_form.save()

        # Сохраняем форму изменения пароля, только если были введены данные
        if password_fields_filled:
            change_password_form.save()
            update_session_auth_hash(request, user)  # Оставляем пользователя авторизованным

        return JsonResponse({'success': True}, status=200)

    else:
        # Если форма не валидна, отправляем ошибки
        errors = {}
        if not user_edit_form.is_valid():
            errors.update(user_edit_form.errors)
        if not profile_edit_form.is_valid():
            errors.update(profile_edit_form.errors)
        if not change_password_form.is_valid():
            errors.update(change_password_form.errors)
        return JsonResponse({'success': False, 'errors': errors}, status=400)


class PasswordResetAjaxView(View):
    def get(self, request, *args, **kwargs):
        form = UserPasswordResetForm()
        html_form = render_to_string('users/password_reset_form.html',
                                     {'form': form}, request=request)
        return JsonResponse({'html_form': html_form})

    def post(self, request, *args, **kwargs):
        form = UserPasswordResetForm(request.POST)
        if form.is_valid():
            form.save(
                request=request,
                email_template_name='users/password_reset_email.html',
                subject_template_name='users/password_reset_subject.txt',
                from_email=settings.DEFAULT_FROM_EMAIL,
            )
            html_reset_done = render_to_string('users/password_reset_done.html', request=request)
            return JsonResponse({'success': True, 'html_reset_done': html_reset_done},
                                status=200)
        else:
            errors = {field: error.get_json_data for field, error in form.errors.items()}
            return JsonResponse({'success': False, 'errors': errors}, status=400)


class PasswordResetConfirmAjaxView(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        # Если пользователь найден, создаем форму для смены пароля
        form = SetPasswordForm(user) if user else None

        # Рендерим форму на страницу
        return render(request, 'users/password_reset_confirm.html', {'form': form})

    def post(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))  # Используем force_str вместо force_text
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        # Создаем форму с новыми данными из POST
        form = SetPasswordForm(user, request.POST)

        if form.is_valid():
            form.save()  # Сохраняем новый пароль
            login(request, user)
            return render(request, 'users/password_reset_complete.html', status=200)
        else:
            return render(request, 'users/password_reset_confirm.html', {'form': form},
                          status=400)


@login_required
def update_photo(request):
    if request.method == "POST" and request.FILES.get("photo"):
        profile = request.user.profile
        profile.photo = request.FILES["photo"]
        profile.save()
        return JsonResponse({"success": True, "photo_url": profile.photo['avatar'].url})
    return JsonResponse({"success": False})


@login_required
def delete_photo(request):
    if request.method == "POST":
        profile = request.user.profile
        profile.photo.delete()  # Удаление файла из БД и системы
        profile.photo = None
        profile.save()
        return JsonResponse({"success": True})
    return JsonResponse({"success": False})

my_bedding/users/templates/users/login_return.html
<!-- Форма входа -->
<div class="tab-content active" id="login">
    <form action="{% url 'users:login' %}" id="login-form" method="post">
        {% csrf_token %}
        <!-- Email -->
        <div class="mb-3 login-form-item">
            <label for="id_email" class="form-label">Email</label>
            <input
                type="email"
                class="form-control"
                id="id_email"
                name="email"
                value="{{ login_form.email.value|default:'' }}">
            <div class="invalid-feedback"></div>
        </div>
        <!-- Пароль -->
        <div class="mb-3 login-form-item">
            <label for="id_password" class="form-label">Пароль</label>
            <div class="input-group">
                <input
                    type="password"
                    class="form-control password-field"
                    id="id_password"
                    name="password">
                <div class="invalid-feedback"></div>
                <button type="button" class="btn" id="toggle-password1">
                    <i class="fa fa-eye"></i> <!-- Иконка глазка -->
                </button>
            </div>
        </div>
        <button type="submit" class="btn-submit">
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="display: none;"></span>
            <span class="button-text">Войти</span>
        </button>
    </form>
    <a href="{% url 'users:password_reset' %}" class="forgot-password-href">
        Забыли пароль?
    </a>
</div>

my_bedding/users/templates/users/password_reset_complete.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>Пароль изменен</h1>

	<p>Вы успешно изменили пароль своего аккаунта. Выполнен вход на сайт.</p>


{% endblock %}

my_bedding/users/templates/users/password_reset_confirm.html
{% extends 'shop/base.html' %}

{% block content %}
	<form id="password-reset-confirm-form" method="post">
	    {% csrf_token %}
	    <div class="mb-3">
	        {{ form.as_p }}
	    </div>
	    <button type="submit" class="btn btn-primary">Изменить пароль</button>
	</form>
{% endblock %}

my_bedding/users/templates/users/password_reset_done.html
<p>На указанный Вами email отправлено письмо для сброса пароля</p>

my_bedding/users/templates/users/password_reset_email.html
{% autoescape off %}
Здравствуйте, {{ user.first_name }}

Вы запросили сброс пароля на сайте MyBedding. Перейдите по следующей ссылке для сброса пароля:<br>

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.
{% endautoescape %}

my_bedding/users/templates/users/password_reset_form.html
<form id="password-reset-form" method="post">
    {% csrf_token %}

    <div class="mb-3">
        <label for="id_email" class="form-label">Введите ваш email</label>
        <input
            type="email"
            name="email"
            id="id_email"
            class="form-control"
            placeholder="Ваш email">
        <div class="invalid-feedback"></div>
    </div>
	<div class="password-reset-links">
		<button type="submit" class="btn btn-primary reset-password-btn">Сбросить пароль</button>
		<a href="#" id="returnToLogin" class="return-to-login">Назад</a>
	</div>
</form>
<style>
#password-reset-form .password-reset-links {
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
}
#password-reset-form .reset-password-btn {
    background-color: #D8BB76;
	border: 1px solid #D7B35E;
	border-radius: 4px;
    color: white;
	{#margin-top: 10px;#}
    {#padding: 10px 20px;#}
    cursor: pointer;
    width: 100%;
	height: 50px;
}
#password-reset-form .reset-password-btn:hover {
	color: #333333; /* Белый текст при наведении */
}
#password-reset-form .return-to-login {
    display: inline-block;
	margin-top: 10px;
    font-size: 16px;
	line-height: 24px;
	font-weight: 450;
    color: #888888;
    text-decoration: none;
}
#password-reset-form .return-to-login:hover {
	color: #333333; /* Белый текст при наведении */
}

</style>