my_bedding/cart/urls.py
from django.urls import path


from .views import (cart_add, cart_detail, cart_remove,
                    cart_increase, cart_decrease, update_quantity,
                    get_discount)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart-detail'),
    path('add/<int:article>/', cart_add, name='cart-add'),
    path('remove/<int:article>/', cart_remove, name='cart-remove'),
    path('increase/<int:article>/', cart_increase, name='cart-increase'),
    path('decrease/<int:article>/', cart_decrease, name='cart-decrease'),
    path('update_quantity/<int:article>/', update_quantity, name='update-quantity'),
    # path('status/', cart_status, name='cart-status'),
    path('get_discount/', get_discount, name='get_discount'),
]

my_bedding/coupons/urls.py
from django.urls import path

from .views import coupon_apply, coupon_remove

app_name = 'coupons'


urlpatterns = [
    path('apply/', coupon_apply, name='apply'),
    path('remove/', coupon_remove, name='remove'),
]

my_bedding/my_bedding/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

my_bedding/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('status/<int:order_id>', views.order_status, name='order_status'),
]

my_bedding/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('catalog/', views.catalog_list, name='cat_list'),
    path('catalog/<slug:cat_slug>/', views.product_list,
         name='product_list_by_cat'),
    path('catalog/<slug:cat_slug>/<int:product_id>/',
         views.product_detail, name='product_detail'),
    path('test/', views.test_view, name='test'),
]

my_bedding/cart/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, HttpResponseRedirect, redirect, \
    get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.http import require_POST

from coupons.forms import CouponForm
from coupons.models import Coupon
from shop.models import Product, ArticleSizeQuantityPrice
from .cart import Cart


@require_POST
def cart_add(request, article):
    article = get_object_or_404(ArticleSizeQuantityPrice, article=article)
    cart = Cart(request)
    cart.add(article_obj=article)
    # Проверяем, добавлен ли товар в корзину
    article_num = str(article.article)
    in_cart = article_num in cart.cart
    context = {'article': article.article, 'in_cart': in_cart}
    # Если товар добавлен в корзину, возвращаем ссылку на cart-detail с золотой иконкой
    # if in_cart:
    #     html = render_to_string('cart/partials/cart_added.html', context, request=request)
    # else:
    #     # Если по какой-то причине товар не добавлен, возвращаем форму с серой иконкой
    #     html = render_to_string('cart/partials/cart_form.html', context, request=request)
    # return HttpResponse(html)
    return JsonResponse({'message': 'Товар добавлен в корзину', 'success': True})


def cart_increase(request, article):
    """Увеличение количества товаров в корзине на 1."""
    article = get_object_or_404(ArticleSizeQuantityPrice, article=article)
    cart = Cart(request)
    if cart.get_quantity(article) < 10:
        cart.add(article)
    return JsonResponse({'quantity': cart.get_quantity(article)})


def cart_decrease(request, article):
    """Уменьшение количества товаров в корзине на 1."""
    article = get_object_or_404(ArticleSizeQuantityPrice, article=article)
    cart = Cart(request)
    cart.reduce(article)
    return JsonResponse({'quantity': cart.get_quantity(article)})


def update_quantity(request, article):
    """Обновление количества товаров в корзине в ручную"""
    article = get_object_or_404(ArticleSizeQuantityPrice, article=article)
    cart = Cart(request)
    try:
        quantity = int(request.POST.get('quantity', 1))
        if quantity < 1:
            quantity = 1
        elif quantity > 10:
            quantity = 10
    except ValueError:
        quantity = 1
    cart.update(article, quantity)
    return JsonResponse({'quantity': cart.get_quantity(article)})


def cart_remove(request, article):
    cart = Cart(request)
    cart.remove(article)
    if not cart.cart:
        request.session['coupon_id'] = None
    # print(cart.cart)
    return JsonResponse({'message': 'Товар удален из корзины', 'success': True})


@never_cache
def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponForm()
    # if 'coupon_id' not in request.session:
    #     request.session['coupon_id'] = None
    context = {
        'cart': cart,
        'coupon_apply_form': coupon_apply_form,
        # 'total_price': cart.get_total_price(),
        # 'discount': cart.get_discount(),
        # 'total_price_after_discount': cart.get_total_price_after_discount(),
        # 'current_path': request.path,
    }
    return render(request, 'cart/cart_detail.html', context)


# def cart_status(request):
#     """Возвращает список артикулов, находящихся в корзине."""
#     cart = Cart(request)
#     articles_in_cart = [item['article'] for item in cart]
#     return JsonResponse({'cart': articles_in_cart})


def get_discount(request):
    cart = Cart(request)
    discount = cart.get_discount()
    if not request.session.get('coupon_id'):
        discount_percentage = 0
        discount_code = ''
    else:
        coupon_id = request.session['coupon_id']
        coupon = Coupon.objects.get(id=coupon_id)
        discount_percentage = coupon.discount
        discount_code = coupon.code
    return JsonResponse({'discount': discount,
                         'discount_percentage': discount_percentage,
                         'discount_code': discount_code})

my_bedding/cart/templates/cart/cart_detail.html
{% extends 'shop/base.html' %}{% load shop_tags_filters %}

{% block content %}
	<div class="container cart-container">
		<div class="cart-left-container">
			{% if cart.cart|length > 0 %}
				<table class="table cart-table caption-top">
					<tbody>
					{% for item in cart %}
						{% with article=item.article product=item.product %}
							<tr id="cart-remove-{{ article.article }}" class="cart-table-tr">
								<td class="cart-table-td">
									{% with product.product_images.all as images %}
										<a href="{% url 'shop:product_detail' product.category.slug product.id %}">
											<img src="{{ images.first.image.url }}" alt="" height="110" width="110"> </a>
									{% endwith %}
								</td>
								<td class="cart-table-td">
									<a href="{% url 'shop:product_detail' product.category.slug product.id %}" class="cart-title">
										<p class="cart-title">{{ product.title }}</p>
									</a>
									<table class="cart-table-params">
										<tr class="cart-params">
											<td class="cart-params-key">Артикул</td>
											<td class="cart-params-value">{{ article.article }}</td>
										</tr>
										<tr class="cart-params">
											<td class="cart-params-key">Размер</td>
											<td class="cart-params-value">{{ article.size.title }}</td>
										</tr>
									</table>
									<div class="accordion" id="accordionExample-{{ article.article }}">
										<div class="accordion-item cart-params">
											<p class="accordion-header">
												<button class="accordion-button collapsed cart-params-key" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne-{{ article.article }}" aria-expanded="false" aria-controls="collapseOne-{{ article.article }}">
													Комплектация
												</button>
											</p>
											<div id="collapseOne-{{ article.article }}" class="accordion-collapse collapse" data-bs-parent="#accordionExample-{{ article.article }}">
												<div class="accordion-body cart-params-value">
													<hr>
													{{ article.equipment|linebreaksbr }}
												</div>
											</div>
										</div>
									</div>
								</td>
								<td class="cart-table-td cart-table-price">
									<div class="cart-item-wrapper">
										<p class="cart-table-items">
											{{ item.price|format_price }} ₽ </p>
										<p class="cart-table-items cart-table-label">
											цена </p>
									</div>
								</td>
								<td class="cart-table-td">
									<div class="cart-item-wrapper">
										<div class="quantity-control cart-table-items">
											<button
												class="btn btn-minus" data-article="{{ article.article }}" type="button">−</button>
											{#<!-- Поле для ввода и отображения количества -->#}
											<input type="number" class="quantity-input" data-article="{{ article.article }}" value="{{ item.quantity }}" min="1" max="{{ article.quantity }}">
											<button class="btn btn-plus" data-article="{{ article.article }}" type="button">+</button>
										</div>
										<p class="cart-table-items cart-table-label">
											количество </p>
									</div>
								</td>
								<td class="cart-table-td">
									<div class="cart-item-wrapper">
										<p class="cart-table-items" data-article="{{ article.article }}" data-price="{{ item.price }}">
											{{ item.total_price|format_price }} ₽ </p>
										<p class="cart-table-items cart-table-label">
											стоимость </p>
									</div>
								</td>
								<td class="cart-table-td cart-detail-links">
									<ul class="cart-detail-links-ul">
										<li>
											<form hx-post=""
												hx-trigger="click"
												hx-swap="none"
												method="post"
												class="add-to-favorite-form">
												{% csrf_token %}
												<button class="add-to-favorite-btn" type="submit" style="border: none; background: none; padding: 0">
													<img src="https://img.icons8.com/?size=23&id=87&format=png&color=8F9999FF" alt="Избранное">
												</button>
											</form>
										</li>
										<li>
	{#										<form#}
	{#											hx-post="{% url 'cart:cart-remove' article.article %}"#}
	{#											hx-trigger="click"#}
	{#											hx-target="#cart-remove-{{ article.article }}"#}
	{#											hx-swap="outerHTML"#}
	{#											class="cart-remove-form">#}
	{#											{% csrf_token %}#}
												<button class="cart-remove-btn" type="submit" style="border: none; background: none; padding: 0">
													<img src="https://img.icons8.com/?size=22&id=11705&format=png&color=8F9999FF" alt="Удалить артикул">
												</button>
	{#										</form>#}
										</li>
									</ul>
								</td>
							</tr>
						{% endwith %}
					{% endfor %}
					</tbody>
				</table>

			{% else %}
				<p class="cart-empty">В корзине пока нет товаров</p>
			{% endif %}
		</div>
		<div class="cart-right-container">
			<div class="cart-final-price">
				<h4>Ваша корзина</h4>
				<div class="promo-code-container">
					<form action="{% url "coupons:apply" %}" method="post" class="coupon-form" id="coupon-form">
						<div class="coupon-label-and-input-container">
							<label for="coupon-code">Промокод</label>
							<input type="text" name="code" id="coupon-code" value="" required>
{#							{{ coupon_apply_form }}#}
							{% csrf_token %}
						</div>
						<div class="coupon-button-container">
							<input
								type="submit"
								value="Применить"
								class="coupon-button"
								id="coupon-button"
								{% if cart|length == 0 %} disabled {% endif %}>
						</div>
					</form>
					<p id="coupon-message"></p>
				</div>

				<div class="cart-final-price-wrapper cart-final-price-wrapper-first">
					<p class="cart-final-price-title">
						Стоимость товаров</p>
					<p id="total-price">
						0 ₽
					</p>
				</div>

				<div class="cart-final-price-wrapper cart-final-price-wrapper-second">
					<p class="cart-final-price-title">
						Скидка (<span id="discount-percentage">0 %</span>) </p>
{#						Скидка ({% discount_percentage %} %) </p>#}
					<p id="discount">
						0 ₽
					</p>
				</div>
				<hr>
				<div class="cart-final-price-wrapper">
					<p class="cart-final-price-title">
						Итоговая стоимость</p>
					<p id="total-price-after-discount">
						0 ₽
					</p>
				</div>

				<div class="cart-final-price-links">
					<form action="{% url 'orders:order_create' %}" method="get">
					    <button
					        type="submit"
					        class="cart-final-price-place-order"
					        id="cart-button"
					        {% if cart|length == 0 %} disabled {% endif %}>
					        Перейти к оформлению
					    </button>
					</form>
{#					<button type="submit" class="cart-final-price-place-order">#}
{#						<a href="{% url 'orders:order_create' %}">Перейти к оформлению</a>#}
{#					</button>#}
					<p class="cart-final-price-continue-shopping">
						<a href="{% url 'shop:product_list' %}">Продолжить покупки</a>
					</p>
				</div>
			</div>
		</div>
	</div>


{% endblock %}