my_bedding/cart/urls.py
from django.urls import path


from .views import (cart_add, cart_detail, cart_remove,
                    cart_increase, cart_decrease, update_quantity,
                    get_discount)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart-detail'),
    path('add/<int:article>/', cart_add, name='cart-add'),
    path('remove/<int:article>/', cart_remove, name='cart-remove'),
    path('increase/<int:article>/', cart_increase, name='cart-increase'),
    path('decrease/<int:article>/', cart_decrease, name='cart-decrease'),
    path('update_quantity/<int:article>/', update_quantity, name='update-quantity'),
    # path('status/', cart_status, name='cart-status'),
    path('get_discount/', get_discount, name='get_discount'),
]

my_bedding/my_bedding/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

my_bedding/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('catalog/', views.catalog_list, name='cat_list'),
    path('catalog/<slug:cat_slug>/', views.product_list,
         name='product_list_by_cat'),
    path('catalog/<slug:cat_slug>/<int:product_id>/',
         views.product_detail, name='product_detail'),
    path('test/', views.test_view, name='test'),
]

my_bedding/users/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path

from .views import (get_csrf_token, register, login_user, logout_user, view_account, edit_account,
                    PasswordResetAjaxView, PasswordResetConfirmAjaxView, update_photo, delete_photo)

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('login-html/', login_user, name='login_html'),
    path('logout/', logout_user, name='logout'),
    path('account/', view_account, name='view_account'),
    path('account/edit/', edit_account, name='edit_account'),
    path('get-csrf-token/', get_csrf_token, name='get_csrf_token'),
    path('password-reset/', PasswordResetAjaxView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmAjaxView.as_view(),
         name='password_reset_confirm'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('update-photo/', update_photo, name='update_photo'),
    path('delete-photo/', delete_photo, name='delete_photo'),
]

my_bedding/shop/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth import get_user_model
from mptt.models import MPTTModel, TreeForeignKey

from . import choices

User = get_user_model()


class Category(MPTTModel):
    """Модель категории товара"""
    parent = TreeForeignKey(
        'self', on_delete=models.PROTECT,
        null=True, blank=True, related_name='children',
        db_index=True, verbose_name='Родительская категория')
    title = models.CharField(
        max_length=100,
        unique=True,
        verbose_name='Название',
    )
    slug = models.SlugField(
        max_length=100,
        unique=True,
        verbose_name='Слаг'
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name='Описание',
    )
    logo = models.ImageField(
        upload_to='categories/',
        blank=True,
        null=True,
        verbose_name='Логотип',
    )

    class MPTTMeta:
        order_insertion_by = ['-id']

    class Meta:
        unique_together = [['parent', 'slug']]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

    def __str__(self):
        return self.title


class ProductSize(models.Model):
    """Модель размеров товаров"""
    title = models.CharField(
        max_length=100,
        verbose_name='Размер товара'
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT,
        related_name='sizes_by_cat',
        verbose_name='Категория'
    )
    description = models.TextField(
        verbose_name='Описание',
        max_length=100
    )
    logo = models.ImageField(
        upload_to='product_sizes/',
        blank=True,
        null=True,
        verbose_name='Картинка'
    )

    class Meta:
        verbose_name = 'Размер товара'
        verbose_name_plural = 'Размеры товаров'

    def __str__(self):
        return self.title


class ArticleSizeQuantityPrice(models.Model):
    """Модель размеров, количеств и цен у артикулов товара"""
    product = models.ForeignKey(
        'Product', on_delete=models.CASCADE,
        related_name='articles',
        verbose_name='Товар',
    )
    article = models.PositiveIntegerField(
        unique=True,
        null=True,
        blank=True,
        validators=[
            MinValueValidator(
                1000000, 'Артикул от 1 000 000'),
            MaxValueValidator(
                9999999, 'Артикул до 10 000 000'),
        ],
        verbose_name='Артикул',
    )
    size = models.ForeignKey(
        ProductSize,
        on_delete=models.CASCADE,
        related_name='articles',
        verbose_name='Размер',
    )
    price = models.PositiveSmallIntegerField(
        verbose_name='Цена',
    )
    quantity = models.PositiveSmallIntegerField(
        default=0, verbose_name='Количество', validators=[MaxValueValidator(
            10000, 'Количество до 10 000 шт.'
        )]
    )
    equipment = models.TextField(
        verbose_name='Комплектация',
        help_text='Каждый элемент комплекта пишите на отдельной строке, '
                  'например:<br>Простыня без резинки (200х220 см) — 1 шт.'
                  '<br>Наволочки (50x70 см) — 2 шт.',
        blank=True,
        null=True,
    )
    shipping_weight = models.CharField(
        max_length=100,
        verbose_name='Упаковка',
        choices=choices.SHIPPING_WEIGHT,
        blank=True,
        null=True,
    )
    gross_weight = models.DecimalField(
        max_length=100,
        max_digits=5,
        verbose_name='Вес с упаковкой, кг',
        blank=True,
        null=True,
        decimal_places=1,
    )

    class Meta:
        verbose_name = 'Артикул'
        verbose_name_plural = ('Артикулы')

    def __str__(self):
        return (f"№ {self.article} ({self.product.title})")

    # def clean(self):
    #     super().clean()
    #     if self.product.category.slug == 'prostyni' and :
    #         raise ValidationError(
    #             'Выберите только один размер: либо размер простыни, '
    #             'либо размер простыни на резинке.'
    #         )
    #     if not self.size and not self.size_elastic:
    #         raise ValidationError(
    #             'Необходимо выбрать один размер: '
    #             'либо размер простыни, '
    #             'либо размер простыни на резинке.'
    #             )


class Product(models.Model):
    """Модель товара"""
    category = TreeForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='products',
        verbose_name='Категории',
    )
    title = models.CharField(
        unique=True,
        max_length=100,
        verbose_name='Название',
    )
    # slug = models.SlugField(
    #     max_length=100,
    #     unique=True,
    #     verbose_name='Слаг',
    # )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True,
    )
    care = models.TextField(
        verbose_name='Уход',
        blank=True,
        null=True,
    )
    is_available = models.BooleanField(
        default=True,
        verbose_name='В продаже',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан'
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Обновлен'
    )

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['id']

    def __str__(self):
        return f"{self.title} (id {self.id})"

    def clean(self):
        super().clean()
        if self.category.children.exists():
            raise ValidationError(
                'У выбранной вами категории есть подкатегории. '
                'Выберите одну из них.'
                )


class ProductParam(models.Model):
    """Модель параметров товара"""
    product = models.OneToOneField(
        Product,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='parameters',
        verbose_name='Товар'
    )
    color = models.CharField(
        max_length=100,
        choices=choices.COLOR,
        verbose_name='Цвет',
        null=True,
    )
    composition = models.CharField(
        max_length=100,
        choices=choices.COMPOSITION,
        verbose_name='Состав',
        null=True,
    )
    design = models.CharField(
        max_length=100,
        choices=choices.DESIGN,
        verbose_name='Дизайн',
        null=True,
    )
    material = models.CharField(
        max_length=100,
        choices=choices.MATERIAL,
        verbose_name='Материал',
        null=True,
    )
    density = models.CharField(
        max_length=100,
        choices=choices.DENSITY,
        verbose_name='Плотность',
        null=True,
    )
    washing_mode = models.CharField(
        max_length=100,
        choices=choices.WASHING_MODE,
        verbose_name='Режим стирки',
        null=True
    )
    type_of_sheet = models.CharField(
        max_length=100,
        choices=choices.TYPE_BED_SHEET,
        verbose_name='Вид простыни (комплекты и простыни)',
        blank=True, null=True,
    )
    presence_of_embroidery = models.CharField(
        max_length=100,
        choices=choices.TOWEL_PRESENCE_OF_EMBROIDERY,
        verbose_name='Наличие вышивки (полотенца)',
        blank=True, null=True,
    )
    filler = models.CharField(
        max_length=100,
        choices=choices.BEDSPREAD_FILLER,
        verbose_name='Наполнитель (покрывала)',
        blank=True, null=True,
    )

    def __str__(self):
        return f"{self.product.title} (id {self.product.id})"

    class Meta:
        verbose_name = 'Параметры товара'
        verbose_name_plural = 'Параметры товаров'


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='product_images',
        verbose_name='Товар'
    )
    image = models.ImageField(
        upload_to='products/%Y/%m/%d/',
        verbose_name='Фото'
    )
    # size = models.CharField(
    #     max_length=10,
    #     choices=(('100x100', '100x100'), ('450x450', '450x450'),
    #              ('1000x1000', '1000x1000')),
    #     verbose_name='Размер',
    # )

    class Meta:
        verbose_name = 'Фотография товара'
        verbose_name_plural = 'Фотографии товара'

    def __str__(self):
        return f"{self.product.title} (id {self.product.id})"

my_bedding/shop/forms.py
# from django.contrib import admin
# from django import forms
# from .models import ProductSizeQuantityPrice, ProductSize, Product


# class ProductSizeQuantityPriceInlineFormSet(forms.BaseInlineFormSet):
#     def get_form_kwargs(self, index):
#         kwargs = super().get_form_kwargs(index)
#         if self.instance.pk:
#             # Получаем продукт и его категорию
#             product = self.instance
#             category = product.category
#             # Фильтруем размеры по категории
#             kwargs['size_queryset'] = ProductSize.objects.filter(category=category)
#         else:
#             kwargs['size_queryset'] = ProductSize.objects.none()
#         return kwargs

my_bedding/shop/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string

from cart.cart import Cart
from shop.models import Product, Category


def catalog_list(request):
    cats = Category.objects.filter(level=0)
    return render(request, 'shop/category/list.html',
                  {'cats': cats})


def product_list(request, cat_slug=None):
    products = Product.objects.filter(is_available=True)
    cart = request.session.get('cart', {})
    context = {'products': products, 'cart': cart}

    if cat_slug:
        category = get_object_or_404(Category, slug=cat_slug)
        descendant_categories = category.get_children()  # Получаем дочерние категории
        all_categories = [category] + list(descendant_categories)
        products = products.filter(category__in=all_categories)  # Фильтруем продукты по категориям
        context.update({'category': category, 'products': products})

        # Пагинация: 8 товаров на страницу
    paginator = Paginator(products, 16)
    page_number = request.GET.get('page', 1)
    try:
        page = paginator.get_page(page_number)
    except (PageNotAnInteger, EmptyPage):
        page = paginator.page(1)

    context.update({'products': page})

    return render(request, 'shop/product/list.html', context)




    # if request.headers.get('x-requested-with') == 'XMLHttpRequest':  # Проверка AJAX-запроса
    #     html = render_to_string('shop/product/_product_cards.html', context=context, request=request)
    #     return JsonResponse({'html': html, 'has_next': page.has_next()})





def product_detail(request, cat_slug, product_id):
    category = get_object_or_404(Category, slug=cat_slug)
    product = get_object_or_404(Product, category=category,
                                id=product_id, is_available=True)
    cart = request.session.get('cart', {})
    return render(request, 'shop/product/detail.html',
                  {'category': category, 'product': product, 'cart': cart})


def test_view(request):
    product_1 = Product.objects.get(id=1)
    return render(request, 'shop/product/test.html',
                  {'product_1': product_1})

my_bedding/shop/templates/shop/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://kit.fontawesome.com/d20f4157cd.js" crossorigin="anonymous"></script>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&display=swap" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<link href="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/css/suggestions.min.css" rel="stylesheet" />
	<script src="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/js/jquery.suggestions.min.js"></script>
	<script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://api-maps.yandex.ru/2.1/?apikey=00d09189-bb88-4114-848c-6a4b55b8d6fa&lang=ru_RU" type="text/javascript"></script>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@cdek-it/widget@3" charset="utf-8"></script>
	<script src="{% static 'styles/medium-zoom.min.js' %}"></script>
	<link rel="stylesheet" href="{% static 'styles/hystmodal.min.css' %}">
	<link rel="stylesheet" href="{% static 'styles/photoswipe.css' %}"> <!-- PhotoSwipe -->
	<script src="https://unpkg.com/htmx.org@2.0.4" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'styles/base.css' %}">
	<script src="{% static 'styles/base.js' %}"></script>
</head>
<body>

<nav class="navbar sticky-top d-flex align-items-center navbar-expand-sm">
    <div class="container-fluid header-nav-container">
        <!-- Логотип и название сайта -->
        <a class="navbar-brand d-flex align-items-center" href="{% url 'shop:product_list' %}">
{#            <img src="{% static '/site/bootstrap-logo.svg' %}" alt="Logo">#}
            <img src="{% static '/site/icons8-клубок-ниток-100.png' %}" alt="Logo">
            <span class="site-name">{{ site_name }}</span>
        </a>
        <!-- Каталог -->
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link catalog-title" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	               <img src="https://img.icons8.com/?size=100&id=36389&format=png&color=555555" alt="" class="menu-icon">

	               <span>Каталог</span>
                </a>
                <ul class="dropdown-menu">
					{% for cat in categories %}
						<li><a class="dropdown-item" href="{% url 'shop:product_list_by_cat' cat.slug %}">
							{{ cat.title}}
						</a></li>
	                {% endfor %}
                </ul>
            </li>
        </ul>

        <!-- Поисковое поле -->
        <form class="d-flex mx-auto search-form">
            <span class="search-icon">
                <i class="fa fa-search"></i>
            </span>
            <input class="form-control me-2" type="search" placeholder="Найти в каталоге" aria-label="Search">
        </form>

        <!-- Иконки -->
        <ul class="navbar-nav ms-auto navbar-nav-icons">

            <!-- Телефон -->
            <li class="nav-item dropdown navbar-nav-first-icon">
                <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
{#                    <i class="fa-solid fa-phone"></i> #}
	                <img src="https://img.icons8.com/?size=100&id=UGjeZAvO94lh&format=png&color=555555" alt="">
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="tel:88000000000" class="dropdown-item">8 800 000 00 00</a>
                    </li>
                </ul>
            </li>

            <!-- Пользователь -->
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'users:view_account' %}">
{#                    <i class="fa-solid fa-user"></i>#}

	                <img src="https://img.icons8.com/?size=100&id=HGBJpD8HuRmK&format=png&color=555555" alt="">
{#	                <img src="https://img.icons8.com/?size=100&id=g579xhV5XKDH&format=png&color=555555" alt="">#}
{#	                <img src="https://img.icons8.com/?size=100&id=gQFqiVQaSZi5&format=png&color=555555" alt="">#}
                </a>
                {% else %}
                <a href="#" class="open-modal-btn nav-link">
{#                    <i class="fa-solid fa-user"></i>#}
	                <img src="https://img.icons8.com/?size=100&id=gQFqiVQaSZi5&format=png&color=555555" alt="">
                </a>
                {% endif %}
            </li>

            <!-- Избранное -->
            <li class="nav-item">
                <a href="#" class="nav-link">
{#                    <i class="fa-solid fa-heart"></i>#}
	                <img src="https://img.icons8.com/?size=100&id=87&format=png&color=555555" alt="">
                </a>
            </li>

            <!-- Корзина -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart-detail' %}">
{#                    <i class="fa-solid fa-cart-shopping"></i> #}
{#	                <img src="https://img.icons8.com/?size=100&id=mlzugiBNw6GO&format=png&color=555555" alt="">#}
	                <img src="https://img.icons8.com/?size=100&id=P6ZYIof6BwLW&format=png&color=555555" alt="">
                </a>
            </li>
        </ul>
    </div>
</nav>


{#<nav class="navbar sticky-top d-flex align-items-center navbar-expand-sm">#}
{#	<div class="container-fluid">#}
{#		<a class="navbar-brand d-flex align-items-center" href="{% url 'shop:product_list' %}">#}
{#			<img src="{% static '/site/bootstrap-logo.svg' %}" alt="Logo"> <span>MyBedding</span> </a>#}
{#		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#			<span class="navbar-toggler-icon"></span>#}
{#		</button>#}
{#		<div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#			<ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">#}
{#				<li class="nav-item">#}
{#					<a class="nav-link" href="{% url 'shop:product_list' %}">Домой</a>#}
{#				</li>#}
{#				<li class="nav-item dropdown">#}
{#					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Сервисы </a>#}
{#					<ul class="dropdown-menu">#}
{#						<li><a class="dropdown-item" href="#">Карта сайта</a></li>#}
{#						<li><a class="dropdown-item" href="#">Новостная RSS-лента</a></li>#}
{#						<li>#}
{#							<hr class="dropdown-divider">#}
{#						</li>#}
{#						<li><a class="dropdown-item" href="{% url 'admin:index' %}">Администратор</a></li>#}
{#					</ul>#}
{#				</li>#}
{#				<li class="nav-item">#}
{#					<a class="nav-link disabled" aria-disabled="true">О сайте</a>#}
{#				</li>#}
{#			</ul>#}
{#			<ul class="navbar-nav ms-auto mb-2 mb-lg-0">#}
{#				<li class="nav-item">#}
{#					{% if user.is_authenticated %}#}
{#						<a href="{% url 'users:view_account' %}">#}
{#							<img src="https://img.icons8.com/?size=25&id=j1b8nUSGHfe0&format=png&color=000000" alt="">#}
{#						</a>#}
{#					{% else %}#}
{#						<a href="#" class="open-modal-btn">#}
{#							<img src="https://img.icons8.com/?size=25&id=j1b8nUSGHfe0&format=png&color=000000" alt="">#}
{#						</a>#}
{#					{% endif %}#}
{##}
{#				</li>#}
{#				<li class="nav-item">#}
{#					<a class="nav-link" href="{% url 'cart:cart-detail' %}">#}
{#						<i class="fa-solid fa-cart-shopping"></i>#}
{#					</a>#}
{#				</li>#}
{#				<li class="nav-item dropdown">#}
{#					<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">#}
{#						<i class="fa-solid fa-magnifying-glass"></i> </a>#}
{#					<ul class="dropdown-menu">#}
{#						<li>#}
{#							<form class="d-flex" role="search">#}
{#								<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#								<button class="btn btn-outline-success" type="submit">Search</button>#}
{#							</form>#}
{#						</li>#}
{#					</ul>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{#</nav>#}

{% include 'users/register_modal.html' %}

<div class="breadcrumbs container">
	<div class="breadcrumbs-title">
		{% if request.path == '/cart/' %}
	        <h2>Корзина</h2>
		{% elif request.path == '/orders/create/' %}
			<h2>Оформление заказа</h2>
		{% elif '/orders/status/' in request.path %}
			<h2>Статус заказа</h2>
		{% elif product %}
			<h2>{{ product.title }}</h2>
		{% elif category %}
			<h2>{{ category.title }}</h2>
		{% elif cats %}
			<h2>Каталог</h2>
		{% else %}
			<h2>Магазин постельного белья MyBedding!</h2>
		{% endif %}
	</div>
	{% if cats or category or product %}
		<a href="{% url 'shop:product_list' %}">Главная</a>
		<span>&nbsp;›&nbsp;</span>
		{% if not category %}
			<span>Каталог</span>
		{% else %}
			<a href="{% url 'shop:cat_list' %}">Каталог</a>
		{% endif %}
	{% endif %}
	{% if category %}
		<span>&nbsp;›&nbsp;</span>
		{% if not product %}
			<span>{{ category.title }}</span>
		{% else %}
			<a href="{% url 'shop:product_list_by_cat' category.slug %}">
				{{ category.title }}</a>
		{% endif %}
	{% endif %}
	{% if product %}
		<span>&nbsp;›&nbsp;</span>
		<span>{{ product.title }}</span>
	{% endif %}
</div>

{% block content %}{% endblock %}

<footer class="site-footer">
    <div class="d-flex site-footer-container">
        <!-- 1 столбец -->
        <div class="footer-column">
            <div class="footer-logo">
                <img src="{% static '/site/icons8-клубок-ниток-100.png' %}" alt="Логотип">
                <span class="site-name">{{ site_name }}</span>
            </div>
            <p class="footer-description footer-description-first">интернет-магазин<br>домашнего текстиля</p>
            <div class="social-links">
                <a href="#" class="social-icon"><i class="fa fa-telegram"></i></a>
                <a href="#" class="social-icon"><i class="fa fa-whatsapp"></i></a>
                <a href="#" class="social-icon"><i class="fa fa-vk"></i></a>
                <a href="#" class="social-icon"><i class="fa fa-odnoklassniki"></i></a>
            </div>
            <p class="footer-description-2">2025 © MyBedding.ru — интернет-магазин<br>домашнего текстиля. Доставка по всей России.</p>
        </div>

        <!-- 2 столбец -->
        <div class="footer-column">
            <p class="column-title">Покупателям</p>
	        <div class="column-items">
	            <a href="#">Способы оплаты</a>
	            <a href="#">Доставка</a>
	            <a href="#">Возврат</a>
	            <a href="#">Публичная оферта</a>
	            <a href="#">Программа лояльности</a>
	            <a href="#">Отслеживание заказа</a>
	        </div>
        </div>

        <!-- 3 столбец -->
        <div class="footer-column">
            <p class="column-title">Компания</p>
	        <div class="column-items">
		        <a href="#">О нас</a>
	            <a href="#">Контакты</a>
	            <a href="#">Бренды</a>
	            <a href="#">Политика конфиденциальности</a>
	            <a href="#">Поставщикам</a>
	        </div>

        </div>

        <!-- 4 столбец -->
        <div class="footer-column">
            <p class="column-title">Контакты</p>
	        <div class="column-items">
		        <div class="footer-phone">
				    <span>Телефон:</span>
				    <a href="tel:88000000000" class="footer-phone">8 800 000 00 00</a>
				</div>
	            <p>Режим работы операторов с 9:00 до 21:00<br>(по московскому времени)</p>
		        <div class="footer-email">
			        <span>Email:</span>
	                <a href="mailto:smaspb17@gmail.com">smaspb17@gmail.com</a>
		        </div>
	        </div>
        </div>
    </div>
</footer>

<script type="module">
    import PhotoSwipeLightbox from '{% static '/styles/photoswipe-lightbox.esm.js' %}';

    const lightbox = new PhotoSwipeLightbox({
        gallery: '#my-gallery',
        children: 'a',
        pswpModule: () => import('{% static '/styles/photoswipe.esm.js' %}')
    });
    lightbox.init();
</script>
<script src="{% static 'styles/hystmodal.min.js' %}"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>